# Generated by Django 4.1.5 on 2023-01-31 11:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Blog Title')),
                ('short_description', models.CharField(max_length=500, verbose_name='Short Describtion')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish Date')),
                ('picture', models.FileField(upload_to='blog/pictures', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('.jpg', '.png', 'jpeg'), message='This File is not Valid')])),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='LikeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('likeview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.likeview')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Blog View Count',
                'verbose_name_plural': 'Blogs View Count',
            },
            bases=('blog.likeview',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('likeview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.likeview')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Blog Like Count',
                'verbose_name_plural': 'Blog Likes Count',
            },
            bases=('blog.likeview',),
        ),
    ]
