# Generated by Django 4.1.5 on 2023-02-03 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Blog Title')),
                ('short_description', models.CharField(max_length=500, verbose_name='Short Describtion')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish Date')),
                ('picture', models.ImageField(upload_to='blog/pictures')),
                ('text', models.TextField(null=True, verbose_name='Text Of Blog')),
                ('active', models.BooleanField(default=True, verbose_name='Blog Activation')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Category Name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog-category/pictures')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Comment Text')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Comment Create Date')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog', verbose_name='Blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory', verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('likeview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.likeview')),
                ('ip', models.CharField(max_length=15, null=True, verbose_name='User Ip')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Blog View Count',
                'verbose_name_plural': 'Blogs View Count',
            },
            bases=('blog.likeview',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('likeview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.likeview')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Blog Like Count',
                'verbose_name_plural': 'Blog Likes Count',
            },
            bases=('blog.likeview',),
        ),
    ]
