# Generated by Django 4.1.5 on 2023-02-02 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_blogcomment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='ip',
            field=models.CharField(max_length=15, null=True, verbose_name='User Ip'),
        ),
        migrations.AlterField(
            model_name='likeview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
