# Generated by Django 4.1.5 on 2023-02-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_view_ip_alter_likeview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Blog Activation'),
        ),
    ]
